version: "3"
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
      - POSTGRES_DB=movies_database
      - PGDATA=/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    env_file:
      - .env.dev
    networks:
      - backend
    expose:
      - 8000
    ports:
      - "8000:8000"
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: swagger/openapi.yaml
    ports:
      - "8080:8080"

volumes:
  pgdata:
      driver: local

networks:
  backend:
