version: "3"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "movies_database"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "123qwe"
    ports:
      - "5432:5432"
